#!/usr/bin/env bash
# Displays "Best School" 10 times but displays Hi after the 9th iteration
i=1
while ((i <= 10))
do
	((i++))
	if [ $i -eq 5 ]
	then
		echo "bad luck"
	elif [ $i -eq 9 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
